### ISSUE TITLE
Cannot run on KDE Neon 5.14 Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by phd21** [Slethen/ProtonVPN-Gtk#20] opened 2018-10-17 03:22 UTC
Hi Slethen,

Thanks for making this interface for ProtonVPN-Cli for everyone to use. I read the other posts under "issues" and agree with those as well.

Unfortunately, on my KDE Neon 5.14 based on Ubuntu 18.04 Bionic it will not run using python or python3.

Best regards,
Phil (phd21)

FYI: Here are the results:

> sudo python ProtonVPN.py

(ProtonVPN.py:6075): Gtk-WARNING **: 22:55:14.635: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(ProtonVPN.py:6075): Gtk-WARNING **: 22:55:14.635: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(ProtonVPN.py:6075): Gtk-WARNING **: 22:55:14.635: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "ProtonVPN.py", line 285, in <module>
    builder.connect_signals(Handler())
  File "ProtonVPN.py", line 90, in __init__
    self.radioBtnSelection(radioSelected="False")
  File "ProtonVPN.py", line 189, in radioBtnSelection
    if str(radioSelected) in (item['Keywords']):
KeyError: 'Keywords'

sudo python3 ProtonVPN.py
  File "ProtonVPN.py", line 25
    except subprocess.CalledProcessError, e:
                                        ^
SyntaxError: invalid syntax

**Comment by joelbduncan** [comment] 2018-10-17 09:29
Hi Phil,

Thanks for your interest, I don't think this is actually relevant to you using KDE.
The GTK Warnings are normal and can be ignored.

I already know what the issue is, Proton changed their unreleased and undocumented API.
I need to work out how to get the same JSON information from there latest API and probably improve the error handling as the information above certainly doesn't point towards that.

I'll keep this bug open as I have been trying to look into sorting this.
I’ll post only updates on this thread :-)

Thanks!

**Comment by joelbduncan** [comment] 2018-10-17 14:30
Hi Paul quick update.

This commit 5de916f8be588cf57efd22f04373f2e861ea5c63 which is in master will hopefully resolve the issue.

I know very little about KDE so please let me know if that allows the Program to run.

Thanks!

**Comment by joelbduncan** [comment] 2018-10-17 14:32
Ah Scrap that theres a hardcoded link, a new issue with the home directorys seems to of appeared.
Theres currently a work around that won't work on your machine.

Sorted in dc67d81eb72bf052a3f72dfa6ceb8ec9774a749b @phd21, feel free to give it ago!

**Comment by phd21** [comment] 2018-10-17 16:32
Hi Slethen,

Thank you for your prompt replies.

Okay, I have some progress.

Background:  I have been using Linux Mint KDE for years and I think all editions of Linux Mint Cinnamon, Mate, Xfce, and KDE are wonderful and stable. But, Linux Mint decided in version 19.x based on Ubuntu 18.04 Bionic forwards to stop producing their KDE desktop version, so I have been testing various KDE systems including adding the KDE desktop to Xfce which also works well. KDE can use either KDE/QT applications or GTK/Gnome applications, usually without issues.

Obviously,  you are using the Python programming environment (with glade?) for this. Are you using Python ver2.x because when I try this with Python3 is does not work. Using Python (Python2), after getting the "Theme parsing errors" and about 20+ seconds,  it shows "Network connection failed" and stalls, but if I hit enter, after another 20+ seconds, then your app comes up and it seems to be working. From the previous "theme" related errors, it looks like you could use different python code or syntax to avoid the "style property ... is deprecated and shouldn't be used anymore" issues.

I'll try to attach the screenshots to this.

Best regards,
Phil (phd21)
phd21mint@gmail.com
![protonvpn-py_1](https://user-images.githubusercontent.com/6324548/47101634-9d929200-d208-11e8-8ae5-ea69f0dc1d12.jpg)
![protonvpn-py_2](https://user-images.githubusercontent.com/6324548/47101635-9d929200-d208-11e8-8107-5a94944a0575.jpg)

**Comment by joelbduncan** [comment] 2018-10-17 17:46
Hi Phil,

No worries!

Interesting that GTK3 apps render so nicely on KDE, haven't had much experience with it myself.
I didn't realise Linux Mint dropped support for KDE, best of luck finding a Distro to stick with.

Yes it's written in Python2 using Glade for the UI.
I think those GTK errors are caused by something Glade adds to the XML.
If you can find what feel free to create a pull request, although I do see this error in a lot of GTK applications.

Glad the program is mostly working!
It's always took a second to start, I'm actually experiencing the same slow start-up after changing to the new API. You shouldn't need to hit enter, just wait for a fair while.

The part of this app holding me back adding more features is my awful implementation of threading for the live status. due to GIL Python can't actually do threading. This may also be linked to the slow start-up.

Any tips of pull requests would be much appreciated.

Thanks

**Comment by phd21** [comment] 2018-10-17 17:59
Hi Slethen,

I remembered that with GTK specific applications and the KDE desktop (Xenial or Bionic) and the "mesa" video updates this year caused major problems with Firefox and other applications not displaying properly and preventing access to menus and toolbar options, etc... especially with GTK2 apps. But, if KDE users installed the GTK2 and GTK3 "adwaita" themes and then under the System Settings - Application Style - Gnome/GTK Application Style changed the settings to Adwaita and Gnome (Apply) then that would help.  FYI: in the new KDE Neon, it required removing the neon-adwaita package.

After I changed the Gnome/GTK to Adwaita, your application came up faster and without the previous GTK messages.

Regards,
Phil (phd21)

![protonvpn-py_kde_use_adwaita_applicationstyle_for_gnome-gtk](https://user-images.githubusercontent.com/6324548/47106547-dc2e4980-d214-11e8-89e9-6117a541cafa.jpg)

![protonvpn-py_kde_use_adwaita_applicationstyle_for_gnome-gtk-2](https://user-images.githubusercontent.com/6324548/47107092-632ff180-d216-11e8-98e9-0e13c95394e6.jpg)

**Comment by joelbduncan** [comment] 2018-10-17 18:08
interesting, I'm looking at speeding up the start-up now. When I tested earlier and experienced slow start-up I was using Fedora in VMware. Which is slow anyway! Now I'm home and using bare metal the start-up time is about a second. That's with Fedora 28 GNOME.

What hardware are you using? I have a fairly powerful PC which doesn't help for testing these kind of problems.

Thanks,

**Comment by phd21** [comment] 2018-10-17 18:18
Hi Slethen,

I just updated my last reply a little.

I am using an ancient underpowered Dell Optiplex 780 usff with only an Intel Core2 Duo E8400, 4gb of system memory, onboard basic video with shared video memory, but I do have an SSDrive which makes a huge difference in speed over older mechanical platter drives. 

FYI: So far, the new Linux KDE Neon OS based on Ubuntu 18.04 Bionic is proving faster than Linux Mint 19 with the KDE desktop or Kubuntu 18.04 and most importantly appears to be stable.

Might be good to switch to Python3 and GTK3 for this?

While researching I came across the articles and posts:

Gtk 3: Theme uses deprecated style properties · Issue #73 · dirruk1/gnome-breeze
https://github.com/dirruk1/gnome-breeze/issues/73

> A temporary fix I applied on my machine:
> Delete the lines in the gtk.css file that use these style properties. It doesn't make a difference anyways since they are ignored by Gtk.
> 

gtk3.py Example - Segmentation Fault - CEF 66.3 Build + Kubuntu 18.04 + libgtk-3.22.30 + Python 2.7.15rc1 64bit - Google Groups
https://groups.google.com/forum/#!topic/cefpython/xC1QA1EDVXw



Thanks for responding so quickly and be friendly. 

Regards,
Phil (phd21)

**Comment by joelbduncan** [comment] 2018-10-19 12:43
Ah interesting that improved the start-up speed. I think I've managed to improve it significantly more I'd love it if you could test it out for me.

A small GUI should run on that hardware fine. Bad code is probably the issue ;-)

I've made some changes to what happens when the application starts-up, all networking code is done in a thread.  9067c811e6e1dcaa5360e1d3c1ef53f3da4d05e6 

If you clone or download the source from https://github.com/Slethen/ProtonVPN-Gtk/tree/startup-disconnect-fix and get back to me that would be awesome.

I've also sorted a issue with the disconnect button freezing the connection status thread. 

Worth noting in that branch I’ve removed a lot of the “try, expect” statements that catch errors.
So there probably be tones of debug in the terminal.

The application is GTK3, I can't a partially big reason to move to Python3 I prefer too.
I find Python2 seems to still be default on a lot of distros too.

Thanks!

**Comment by phd21** [comment] 2018-10-24 00:07
Hi Slethen,

I hope this finds you and yours doing well.

I finally got a chance to test this branch, this is the command I used.
git clone -b startup-disconnect-fix https://github.com/Slethen/ProtonVPN-Gtk.git

It seems to be working, I can connect and disconnect, but it keeps displaying 'Updating" for some reason in the console terminal?

It would also be nice if it displayed the IP Address and Country on the main screen without having to click the menu button. And, it would be nice to have an icon in the system tray with mouse over pop-up with IP Address and Country, and green if connected and red if disconnected... Perhaps being able to run it from a desktop shortcut launcher without sudo instead of from a console terminal, but have it ask 
for sudo permission on first launch.

Best regards,
Phil (phd21)

![protonvpn-gtk_10232018-1](https://user-images.githubusercontent.com/6324548/47397895-743d9e80-d6ff-11e8-9e8d-5d6af92f3693.jpg)

**Comment by joelbduncan** [comment] 2018-10-24 10:36
You can now use master again, this and a few other mods have been pushed to master.

As I said it still contains debug code :). That "Updating" message comes from the thread that updates the GTK GUI's connection status, IP & Country. It just confirms it's working. I'll remove it from master soon.

I can look into integrating that information into the GUI again possibly.

Unfortunately, because the application is designed for GNOME it will likely never have a "Status Indicator". I really wanted to have one but GNOME dropped support for it a while ago.

I haven’t managed to find a way to ask for root permission, if you can think of anything drop it under the existing issue or even better make a pull request that would be awesome! It’s not as simple as using GkSudo as it no longer in a lot of distros including the one I use.
This issue is holding me back on making “Connected/Disconnected” nonfictions as the notification daemon can’t be used a root.

I'll probably close this issue as I believe the original problem has been solved :)

Thanks!

**Closed as completed** 2018-12-03 15:21 UTC
